blank_issues_enabled: false
contact_links:
  - name: Projektin suunnittelukysymykset
    url: https://github.com/codenamey/webshop/discussions
    about: Käytä keskusteluja avoimiin suunnittelu- ja toteutuskysymyksiin, jos Discussions on käytössä.
